SwiftyNames.V1.0/SwiftyNames.V1.0/Controllers/AdminController.cs
using SwiftyNames.V1._0.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwiftyNames.V1._0.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        SwiftyNamesEntities Db = new SwiftyNamesEntities();
        //
        // GET: /Admin/
        [HttpGet]

        public ActionResult AdminPage()
        {
            ChangeName model = new ChangeName();
            var list = AdminReview();
            model.ChangeList = list;
            model.StartDate = DateTime.Today;
            model.EndDate = DateTime.Today;
            return View(model);

        }

        public List<ChangeName> AdminReview()
        {
            List<ChangeName> list = new List<ChangeName>();

            List<CustomerDetail> Namelist = Db.CustomerDetails.OrderByDescending(x => x.InfoId).ToList();
            foreach (var x in Namelist)
            {
                ChangeName model = new ChangeName();
                model.InfoId = x.InfoId;
                model.Date = x.Date;
                model.Phone = x.Phone;
                model.SessionKey = x.SessionKey;
                model.newsName = NewsPaperbyId(x.NewsPaperId);
                model.DayName = DaybyId(x.DayId);
                model.NewFullName = x.NewFullName;
                model.OldFullName = x.OldFullName;
                model.Address = x.Address;
                model.Email = x.Email;
                list.Add(model);

            }
            return list;
        }

        private string NewsPaperbyId (int Id)
        {
            var query = from category in Db.NewsPapersPrices
                        where category.Id == Id
                        select category;
            var content = query.ToList<NewsPapersPrice>();
            return content.SingleOrDefault().NewsPaper;
        }

        private string DaybyId(int Id)
        {
            var query = from category in Db.DayTypes
                        where category.DayTypeId == Id
                        select category;
            var content = query.ToList<DayType>();
            return content.SingleOrDefault().Day;
        }
        [HttpPost]
        public ActionResult AdminPage(ChangeName mode)
        {

            List<ChangeName> list = new List<ChangeName>();
            if (mode.StartDate != null && mode.EndDate != null) ;
            var query = Db.CustomerDetails.Where(emp => emp.Date >= mode.StartDate && emp.Date <= mode.EndDate);
           
                  
            foreach (var x in query)
            {
                ChangeName model = new ChangeName();

               
                model.InfoId = x.InfoId;
                model.Date = x.Date;
                model.Phone = x.Phone;
                model.SessionKey = x.SessionKey;
                model.newsName = NewsPaperbyId(x.NewsPaperId);
                model.DayName = DaybyId(x.DayId);
                model.DayId = x.DayId;
                model.Address = x.Address;
                model.NewFullName = x.NewFullName;
                model.OldFullName = x.OldFullName;
                model.Email = x.Email;
                list.Add(model);

            }
            mode.ChangeList = list;

            return View(mode);
        }
    }
}

SwiftyNames.V1.0/SwiftyNames.V1.0/Controllers/SearchController.cs
using System;
using System.Globalization;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.Owin.Security;
using SwiftyNames.V1._0.Models;
using System.Collections.Generic;
namespace SwiftyNames.V1._0.Controllers
{
    [Authorize]
    public class SearchController : Controller
    {
        SwiftyNamesEntities Db = new SwiftyNamesEntities();
        private ApplicationUserManager _userManager;

        public SearchController()
        {
        }

        public SearchController(ApplicationUserManager userManager, ApplicationSignInManager signInManager)
        {
            UserManager = userManager;
            SignInManager = signInManager;
        }

        public ApplicationUserManager UserManager
        {
            get
            {
                return _userManager ?? HttpContext.GetOwinContext().GetUserManager<ApplicationUserManager>();
            }
            private set
            {
                _userManager = value;
            }
        }

        //
        // GET: /Account/Login
       


        // GET: CustomerDetails
        [HttpGet]
        public ActionResult Search()
        {
            ChangeName model = new ChangeName();
            var list = customer();
            model.customerlist = list;
            return View(model);
        }
        private string NewsPaperbyImage(int Id)
        {
            var query = from category in Db.NewsPapersPrices
                        where category.Id == Id
                        select category;
            var content = query.ToList<NewsPapersPrice>();
            return content.SingleOrDefault().PaperImage;
        }
        [HttpPost]
        public ActionResult Search(ChangeName mode)
        {

            List<ChangeName> list = new List<ChangeName>();
            var r = Db.CustomerDetails.Where(emp => emp.OldFullName.Contains(mode.Search)).ToList();
            foreach (var a in r)
            {
                ChangeName model = new ChangeName();
                model.InfoId = a.InfoId;
                model.Email = a.Email;            
                model.Phone = a.Phone;
                model.newsImage = NewsPaperbyImage(a.NewsPaperId);
                model.OldFullName = a.OldFullName;
                model.NewFullName = a.NewFullName;
                list.Add(model);

            }
            mode.customerlist = list;

            return View(mode);
        }
        public List<ChangeName> customer()
        {
            List<ChangeName> list = new List<ChangeName>();
            List<CustomerDetail> objlist = Db.CustomerDetails.OrderByDescending(x => x.InfoId).ToList();

            foreach (var a in objlist)
            {
                ChangeName model = new ChangeName();
                model.InfoId = a.InfoId;
                model.Email = a.Email;
                model.Phone = a.Phone;
                model.newsImage = NewsPaperbyImage(a.NewsPaperId);
                model.OldFullName = a.OldFullName;
                model.NewFullName = a.NewFullName;
               // list.Add(model);

            }
            return list;
        }
        [AllowAnonymous]
        public ActionResult SearchLogin(string returnUrl)
        {
            ViewBag.ReturnUrl = returnUrl;
            return View();
        }

        private ApplicationSignInManager _signInManager;

        public ApplicationSignInManager SignInManager
        {
            get
            {
                return _signInManager ?? HttpContext.GetOwinContext().Get<ApplicationSignInManager>();
            }
            private set { _signInManager = value; }
        }

        //
        // POST: /Account/Login
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SearchLogin(SearchLoginViewModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // This doesn't count login failures towards account lockout
            // To enable password failures to trigger account lockout, change to shouldLockout: true
            var result = await SignInManager.PasswordSignInAsync(model.Email, model.Password, model.RememberMe, shouldLockout: false);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(returnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.RequiresVerification:
                    return RedirectToAction("SendCode", new { ReturnUrl = returnUrl, RememberMe = model.RememberMe });
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid login attempt.");
                    return View(model);
            }
        }

        //
        // GET: /Account/VerifyCode
        [AllowAnonymous]
        public async Task<ActionResult> VerifyCode(string provider, string returnUrl, bool rememberMe)
        {
            // Require that the user has already logged in via username/password or external login
            if (!await SignInManager.HasBeenVerifiedAsync())
            {
                return View("Error");
            }
            var user = await UserManager.FindByIdAsync(await SignInManager.GetVerifiedUserIdAsync());
            if (user != null)
            {
                var code = await UserManager.GenerateTwoFactorTokenAsync(user.Id, provider);
            }
            return View(new SearchVerifyCodeViewModel { Provider = provider, ReturnUrl = returnUrl, RememberMe = rememberMe });
        }

        //
        // POST: /Account/VerifyCode
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> VerifyCode(SearchVerifyCodeViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            // The following code protects for brute force attacks against the two factor codes. 
            // If a user enters incorrect codes for a specified amount of time then the user account 
            // will be locked out for a specified amount of time. 
            // You can configure the account lockout settings in IdentityConfig
            var result = await SignInManager.TwoFactorSignInAsync(model.Provider, model.Code, isPersistent: model.RememberMe, rememberBrowser: model.RememberBrowser);
            switch (result)
            {
                case SignInStatus.Success:
                    return RedirectToLocal(model.ReturnUrl);
                case SignInStatus.LockedOut:
                    return View("Lockout");
                case SignInStatus.Failure:
                default:
                    ModelState.AddModelError("", "Invalid code.");
                    return View(model);
            }
        }

        //
        // GET: /Account/Register
        [AllowAnonymous]
        public ActionResult SearchRegister()
        {
            return View();
        }

        //
        // POST: /Account/Register
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> SearchRegister(SearchRegisterViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new ApplicationUser { UserName = model.Email, Email = model.Email };
                var result = await UserManager.CreateAsync(user, model.Password);
                if (result.Succeeded)
                {
                    await SignInManager.SignInAsync(user, isPersistent: false, rememberBrowser: false);

                    // For more information on how to enable account confirmation and password reset please visit http://go.microsoft.com/fwlink/?LinkID=320771
                    // Send an email with this link
                    string code = await UserManager.GenerateEmailConfirmationTokenAsync(user.Id);
                    var callbackUrl = Url.Action("ConfirmEmail", "Account", new { userId = user.Id, code = code }, protocol: Request.Url.Scheme);
                    await UserManager.SendEmailAsync(user.Id, "Confirm your account", "Please confirm your account by clicking <a href=\"" + callbackUrl + "\">here</a>");

                    return RedirectToAction("Index", "Home");
                }
                AddErrors(result);
            }

            // If we got this far, something failed, redisplay form
            return View(model);
        }

        //
        // GET: /Account/ConfirmEmail
        [AllowAnonymous]
        public async Task<ActionResult> ConfirmEmail(string userId, string code)
        {
            if (userId == null || code == null)
            {
                return View("Error");
            }
            var result = await UserManager.ConfirmEmailAsync(userId, code);
            return View(result.Succeeded ? "ConfirmEmail" : "Error");
        }

        //
        // GET: /Account/ForgotPassword
        [AllowAnonymous]
        public ActionResult ForgotPassword()
        {
            return View();
        }

        //
        // POST: /Account/ForgotPassword
        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> ForgotPassword(SearchForgotPasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await UserManager.FindByNameAsync(model.Email);
                if (user == null || !(await UserManager.IsEmailConfirmedAsync(user.Id)))
                {
                    // Don't reveal that the user does not exist or is not confirmed
                    return View("ForgotPasswordConfirmation");
                }

SwiftyNames.V1.0/SwiftyNames.V1.0/Views/Admin/AdminPage.cshtml
@model SwiftyNames.V1._0.Models.ChangeName

@{
    ViewBag.Title = "";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link href="~/css/style.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
}

<div class="container">
    <div class="nav nav-bar">

        <div class="main-menu">

            <ul style="background: #02230c; font-family:Cambria; color:white; ">
                <li><img src="/images/LOGO1.png" /></li>
                <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                @*<li>@Html.ActionLink("ABOUT", "About", "Home")</li>*@
                <li>@Html.ActionLink("CATALOGUE", "CatalogView", "NamesCatalog")</li>
                <li>@Html.ActionLink("CHANGE NAME", "NewsSearch", "Change")</li>
                <li>@Html.ActionLink("SEARCH NAMES", "SearchLogin", "Search")</li>
                <li>@Html.ActionLink("PUBLIC NOTICE", "PublicNewsSearch", "Home")</li>
                @*<li>@Html.ActionLink("FAQ", "Index", "Home")</li>*@

            </ul>
        </div> <!-- /.main-menu -->

    </div>
</div>

<div class="container">
    <div class="panel panel-default text-uppercase">

        <div class="panel-heading" style="font-size:xx-large">
            Changed Name History


        </div>

        <div class="panel-body">
            <div class="col-lg-offset-0 col-lg-12">

                @using (Ajax.BeginForm("AdminPage", "Admin", new AjaxOptions { HttpMethod = "post" }, new { @class = "form-inline", @id = "formId" }))
            {
                    <div class="form-group date" id="">
                        @Html.LabelFor(x => x.StartDate, new { @class = "" })
                        @Html.TextBoxFor(model => model.StartDate, "{0:dd/MM/yyyy}", new { @Id = "datetime1", @class = "form-control input-sm" })
                        @*<div class="input-group-addon picker"><span class="glyphicon glyphicon-th" aria-hidden="true"></span></div>*@
                    </div>
                    <div class="form-group col-lg-offset-1">
                        @Html.LabelFor(x => x.EndDate, new { @class = "" })
                        @Html.TextBoxFor(model => model.EndDate, "{0:dd/MM/yyyy}", new { @Id = "datetime2", @class = "form-control input-sm" })
                        @*<div class="input-group-addon picker"><span class="glyphicon glyphicon-th" aria-hidden="true"></span></div>*@
                    </div>

                    <div class="form-group col-lg-offset-1">
                        <br />
                        <input type="submit" value="Search" class="btn btn-primary form-control" id="butt" />
                    </div>

            }
                <br />
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>@Html.DisplayNameFor(model => model.OldFullName)</th>
                            @* <th>@Html.DisplayNameFor(model => model.OldFirstName)</th>*@
                            @* <th>@Html.DisplayNameFor(model => model.OldMiddleName)</th>*@

                            @* <th>@Html.DisplayNameFor(model => model.NewLastName)</th>*@

                            @* <th>@Html.DisplayNameFor(model => model.NewFirstName) </th>*@
                            <th>@Html.DisplayNameFor(model => model.NewFullName)</th>
                            <th>@Html.DisplayNameFor(model => model.Address)</th>
                            <th>@Html.DisplayNameFor(model => model.newsName)</th>
                            <th>@Html.DisplayNameFor(model => model.DayName)</th>
                            <th>@Html.DisplayNameFor(model => model.Date)</th>


                        </tr>


                    </thead>
                    <tbody>
                        @foreach (var item in Model.ChangeList)
                    {
                            <tr>

                                <td>@Html.DisplayFor(m => item.OldFullName)</td>
                                @*<td>@Html.DisplayFor(m => item.OldLastName)</td>*@
                                @* <td>@Html.DisplayFor(m => item.OldMiddleName)</td>*@
                                <td>@Html.DisplayFor(m => item.NewFullName)</td>
                                @*<td>@Html.DisplayFor(m => item.NewLastName)</td>*@
                                @*<td>@Html.DisplayFor(m => item.NewMiddleName)</td>*@
                                <td>@Html.DisplayFor(m => item.Address)</td>
                                <td>@Html.DisplayFor(m => item.newsName)</td>
                                <td>@Html.DisplayFor(m => item.DayName)</td>
                                <td>@Html.DisplayFor(m => item.Date)</td>


                            </tr>

                    }

                    </tbody>
                </table>


            </div>
            <div class="col-lg-offset-0 col-lg-12">
                <button class="bth btn-primary" id="print">Print</button>
            </div>
        </div>

    </div>
</div>
<script type="text/javascript">
  


    $("#print").click(function () {
        $(".well").hide();
        $('#formId').hide();
        window.print();
    });

   

</script>