SwiftyNames.V1.0/SwiftyNames.V1.0/Models/ChangeName.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SwiftyNames.V1._0.Models
{
    public class ChangeName
    {
       
        public IEnumerable<SelectListItem> Day { get; set; }
        public IEnumerable<SelectListItem> NewsPapers { get; set; }

     
        public int InfoId { get; set; }
        [Display(Name="Newspaper")]
        public string newsName { get; set; }
        public string newsImage { get; set; }
        [Display(Name = "Day")]
       
        public string DayName { get; set; }
        [Display(Name = "Former Full Name")]
        public string OldFullName { get; set; }
        [Display(Name = "New Full Name")]
        public string NewFullName { get; set; }

       

        [Display(Name = "Address")]
        [Required(ErrorMessage = "This field is required.")]
        public string Address { get; set; }

        [Display(Name = "Phone Number")]
        [Required]
        [RegularExpression("[0-9]{11}")]
        public string Phone { get; set; }

        public string SessionKey { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        public int NewsPaperId { get; set; }
        [EmailAddress(ErrorMessage = " A valid email address is required.")]
        [Required]
        [Display(Name = "E-Mail Address")]
        public string Email { get; set; }

        public int DayId { get; set; }
        [Required]
        public DateTime Date { get; set; }

        public List<ChangeName> ChangeList { get; set; }
        public List<ChangeName> CatalogList { get; set; }
       
        public DateTime StartDate { get; set; }
        public DateTime EndDate { get; set; }
        public List<ChangeName> NewsPaperlist { get; set; }
        public List<ChangeName> customerlist { get; set; }
        public List<ChangeName> newslist { get; set; }
        [Display(Name = "SEARCH")]
        public string Search { get; set; }
        public int Id { get; set; }
        public string NewsPaper { get; set; }
        public string PaperImage { get; set; }
     
        public string PriceTag { get; set; }
        public string NewsPaperName { get; set; }
        public string PaperImageName { get; set; }
        public decimal Price { get; set; }
        public string PriceTagName { get; set; }
        public string PaperSlogan { get; set; }
        public string NoticePrice { get; set; }
        public int NoticeId { get; set; }
        public string NoticeName { get; set; }

        [Display(Name = "Phone Number")]
        [Required(ErrorMessage = "This field is required.")]
        [RegularExpression("[0-9]{11}")]
        public string NoticePhone { get; set; }
        [Required(ErrorMessage = "This field is required.")]
        [Display(Name = "E-Mail Address")]
        [EmailAddress]
        public string NoticeEmail { get; set; }

        [MaxLength (200, ErrorMessage="Not more than 200 words") ]
        [Display(Name = "Address")]
        [Required(ErrorMessage = "This field is required.")]
        public string NoticeWord { get; set; }

        public int NoticeDayId { get; set; }
        public int NoticePaperId { get; set; }
        public DateTime  NoticeDate{get; set;}
    }
}

SwiftyNames.V1.0/SwiftyNames.V1.0/Controllers/NamesCatalogController.cs
using SwiftyNames.V1._0.Models;
using SwiftyNames.V1._0.Persistants;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;


namespace SwiftyNames.V1._0.Controllers
{
    
    public class NamesCatalogController : Controller
    {
        

        SwiftyNamesEntities context = new SwiftyNamesEntities();
        //private Logics logic;
        // GET: NamesCatelog

        
       
        

        public ActionResult CatalogView()
        {
            ChangeName model = new ChangeName();
            var list = CatalogReview();
            model.CatalogList = list;
            return View(model);
           
        }
        public List<ChangeName> CatalogReview()
        {
            List<ChangeName> list = new List<ChangeName>();

            List<CustomerDetail> Namelist = context.CustomerDetails.OrderByDescending(x => x.InfoId).ToList();
            foreach (var x in Namelist)
            {
                ChangeName model = new ChangeName();
                model.InfoId = x.InfoId;
                model.Date = x.Date;
                model.Phone = x.Phone;
                model.SessionKey = x.SessionKey;
                model.NewFullName = x.NewFullName;
                model.OldFullName = x.OldFullName;
                model.Address = x.Address;
                model.Email = x.Email;
                list.Add(model);

            }
            return list;
        }

       
        private void BindCombo(NewsPaperModel model, IList<NewsPapersPrice> AvailableNewsPaper)
        {
            List<NewsPapersPrice> importname = new List<NewsPapersPrice>();
            model.NewsPapers = new MultiSelectList(AvailableNewsPaper, "Id", "NewsPaper","Price", importname.Select(x => x.Id));

        }
        [HttpGet]
        public ActionResult AvailableNewsPaper()
        {
             NewsPaperModel model = new NewsPaperModel();
             List<NewsPapersPrice> newspapers = new List<NewsPapersPrice>();
             newspapers = context.NewsPapersPrices.ToList();
             model.PriceList = new MultiSelectList(newspapers, "Id","Price",newspapers.Select(x => x.Id));
             model.NewsPapers = new MultiSelectList(newspapers, "Price", "NewsPaper", newspapers.Select(x => x.PriceTag));
             ViewBag.delievery = "Do you want it delivered to your address";
             return View(model);
        }

        [HttpPost]
        public ActionResult AvailableNewsPaper(NewsPaperModel model)
        {
            
            Delivery deliver = new Delivery();
            if(!string.IsNullOrEmpty(model.Address) && !string.IsNullOrEmpty(model.phoneNumber))
            {
                deliver.Address = model.Address;
                deliver.PhoneNumber = model.phoneNumber;
                deliver.DateOrdered = DateTime.Now;
                context.Deliveries.Add(deliver);
                context.SaveChanges();
                TempData["success"] = "Your NewsPaper will be delivered to the given address in three days you can now proceed to payment";
            }

            List<NewsPapersPrice> newspapers = new List<NewsPapersPrice>();
            newspapers = context.NewsPapersPrices.ToList();
            model.PriceList = new MultiSelectList(newspapers, "Id", "Price", newspapers.Select(x => x.Id));
            model.NewsPapers = new MultiSelectList(newspapers, "Price", "NewsPaper", newspapers.Select(x => x.PriceTag));
            ViewBag.delievery = "Do you want it delivered to your address";
            model.phoneNumber = string.Empty;
            model.Address = string.Empty;

            return View(model);
        }
        public ActionResult ChangeOfNamey()
        {
            return View();
        }
        private IEnumerable<SelectListItem> Nationalitems (NameChanger model)
        {
            List<Nationality> national = new List<Nationality>();
            national = context.Nationalities.Where(x => x.Adjective != null && x.Abbreviation!="-").ToList();
            var  list = from s in national
                        select new SelectListItem
                        {
                            Selected = s.NationalityId.ToString() == model.CountryId.ToString(),
                            Text = s.Adjective,
                            Value = s.NationalityId.ToString()
                        };
            model.Nationality = "Nigerian";
            return list;
        }
        private IEnumerable<SelectListItem> NewsPaper(NameChanger model)
        {
            List<NewsPapersPrice> dailies = new List<NewsPapersPrice>();
            dailies = context.NewsPapersPrices.ToList();
            var list = from s in dailies
                       select new SelectListItem
                       {
                           Selected = s.Id.ToString() == model.NewsId.ToString(),
                           Text = s.NewsPaper,
                           Value = s.Id.ToString()
                       };
           
            return list;
        }
        private IEnumerable<SelectListItem> countryItems(NameChanger model)
        {
            List<Nationality> national = new List<Nationality>();
            national = context.Nationalities.Where(x => x.Adjective != null && x.Adjective!="-").ToList();
            var list = from s in national
                       select new SelectListItem
                       {
                           Selected = s.NationalityId.ToString() == model.CountryId.ToString(),
                           Text = s.Country,
                           Value = s.NationalityId.ToString()
                       };
            model.country = "Nigeria";
            return list;
        }
        private IEnumerable<SelectListItem> HomeCountry(NameChanger model)
        {
            List<Nationality> national = new List<Nationality>();
            national = context.Nationalities.Where(x =>x.Country=="Nigeria").ToList();
            var list = from s in national
                       select new SelectListItem
                       {
                           Selected = s.NationalityId.ToString() == model.CountryId.ToString(),
                           Text = s.Country,
                           Value = s.NationalityId.ToString()
                       };
           
            return list;
        }
        private IEnumerable<SelectListItem> StatesList(NameChanger model)
        {
            List<State> national = new List<State>();
            national = context.States.ToList();
            var list = from s in national
                       select new SelectListItem
                       {
                           Selected = s.Id.ToString() == model.stateId.ToString(),
                           Text = s.StateName,
                           Value = s.Id.ToString()
                       };
           
            return list;
        }

        private IEnumerable<SelectListItem> NoticeList(NameChanger model)
        {
            List<State> national = new List<State>();
            national = context.States.ToList();
            var list = from s in national
                       select new SelectListItem
                       {
                           Selected = s.Id.ToString() == model.stateId.ToString(),
                           Text = s.StateName,
                           Value = s.Id.ToString()
                       };

            return list;
        }
        
        private List<SelectListItem> bindComboDate()
        {
            var listItems = new List<SelectListItem>
         {
          new SelectListItem { Text = "During the week", Value="1" },
          new SelectListItem { Text = "Weekends", Value="2" },
        
          };
            return listItems;
        }

        private List<SelectListItem> bindComboHear()
        {
            var listItems = new List<SelectListItem>
         {
          new SelectListItem { Text = "Radio", Value="1" },
          new SelectListItem { Text = "NewsPaper", Value="2" },
          new SelectListItem { Text = "Facebook", Value="3" },
          new SelectListItem { Text = "Blog", Value="4" },
          new SelectListItem { Text = "LinkedIn", Value="5" },
          new SelectListItem { Text = "Youtube", Value="5" },
          new SelectListItem { Text = "Others", Value="6" },
        
          };
            return listItems;
        }
       
        private List<SelectListItem> bindCombo()
        {
            var listItems = new List<SelectListItem>
         {
          new SelectListItem { Text = "No", Value="0" },
          new SelectListItem { Text = "Yes", Value="1" },
        
          };
            return listItems;
        }
      
        [HttpGet]
        public ActionResult ChangeOfNameForm()
        {
            NameChanger model = new NameChanger();
            List<Nationality> national = new List<Nationality>();
            national = context.Nationalities.Where(x=>x.Adjective!=null).ToList();
            model.NAtionalities = Nationalitems(model);

            model.countries = countryItems(model);
            model.Homecountries = HomeCountry(model);
            model.StateList = StatesList(model);
            model.NewsPapers = NewsPaper(model);

            model.AreyoumarriedList = bindCombo();
            model.LegalpuporseList = bindCombo();
            model.ConvictedList = bindCombo();
            model.DivoiceList = bindCombo();
            model.Hearabout = bindComboHear();
          

            List<NoticeLevel> notices = new List<NoticeLevel>();
            notices = context.NoticeLevels.ToList();
            model.NoticeLevel = new MultiSelectList(notices, "Id", "NoticeName", notices.Select(x => x.Id));

            List<Reason> Reasons = new List<Reason>();
            Reasons = context.Reasons.ToList();
            model.Reasons = new MultiSelectList(Reasons, "Id", "NameChangeReasons", Reasons.Select(x => x.Id));

SwiftyNames.V1.0/SwiftyNames.V1.0/Views/NamesCatalog/AvailableNewsPaper.cshtml
@model SwiftyNames.V1._0.Models.NewsPaperModel
@{
    
    ViewBag.Title = "AvailableNewsPaper";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div>
    @if (TempData["Success"] != null)
    {
        <div class="alert alert-success">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            @TempData["Success"];
        </div>
    }
</div>
    <h3 class="col-lg-offset-1">Available News Paper</h3>
    <div class="col-lg-12">
        <div id="listbox" class="text-primary col-lg-offset-1" style="height:400px;">

            <table class="table table-condensed text-justify text-uppercase style=" border:none">
                <tr class="text-justify text-primary">
                    <td>NEWS PAPERS</td>
                    <td>PRICE</td>
                </tr>
            </table>
            <hr />
            <div>
                @foreach (var item in Model.NewsPapers)
                {
                    var insertme = item.Selected ? "checked=\"checked\"" : @String.Empty;
                    var forname = "for=\"group" + @item.Value + "\"";
                    var idName = "id=\"group" + @item.Value + "\"";

                    <ul class="list-unstyled">
                        <li style="font-size:large">

                            <label class="checkbox" @forname>
                                <input id="checker" type="checkbox" name="groups" value="@item.Value"
                                       @idName @insertme />
                                @item.Text
                            </label>
                        </li>
                    </ul>
                }
            </div>
            <div class="col-lg-offset-8" style="margin-top:-7em">

                @foreach (var item in Model.PriceList)
                {
                    var insertme = item.Selected ? "checked=\"checked\"" : @String.Empty;
                    var forname = "for=\"group" + @item.Value + "\"";
                    var idName = "id=\"group" + @item.Value + "\"";
                    <ul class="list-unstyled">
                        <li style="list-style: none; font-size:large">
                            <label @forname>
                                &#x20a6 @item.Text
                            </label>
                        </li>
                    </ul>
                }
            </div>

            <div class="text-success col-lg-offset-8" style="font-size:medium">Total Amount</div>
            <div class="text-capitalize col-lg-offset-8" id="price" style="border:solid 1px;height:28px;width:275px;font-size:large"></div>

            <input class="btn btn-success btn-block col-lg-offset-8" type="button" style="margin-top:5px" value="PROCEED TO PAYMENT" />
            @*<div style="margin-top:-6.5em">
                <label>Do you want it to be delivered to your address?</label>
                <div class="checkbox">
                    <label class="checkbox-label">YES</label><input type="checkbox" id="yes" value="500" data-toggl />
                </div>

                <div>
                    <input type="checkbox" id="no" value="0" /><label class="checkbox-label">NO</label>
                </div>
            </div>

            <br />
            <div id="form">
                @using (Ajax.BeginForm("AvailableNewsPaper", "NamesCatalog", new AjaxOptions { HttpMethod = "post" }))
                {
                    <div>
                        @Html.LabelFor(x => x.phoneNumber, new { })
                        @Html.TextBoxFor(x => x.phoneNumber, new { @class = "form-control" })

                    </div>
                    <div>
                        @Html.LabelFor(x => x.Address, new { })
                        @Html.TextAreaFor(x => x.Address, new { @class = "form-control" })
                    </div>
                    <div>
                        <br />
                        <input type="submit" value="Submit" class="btn btn-primary btn-block form-control" />
                    </div>
                }
            </div>*@
        </div>

    </div>
    <script>
        $(document).ready(function () {
            $("input:checkbox:checked").attr("checked", false);
            $("form").hide();
        });
        jQuery("input[type=checkbox]").click(function () {
            var totali = 0;
            jQuery("input[type=checkbox]:checked").each(function () {


                totali += parseFloat(jQuery(this).val());

            });

            jQuery('#price').html(totali + '&#x20a6');
            //$("#yes").click(function () {
            //    if (this.checked) {

            //        totali += parseFloat(jQuery(this).val());
            //        $('#no').prop('checked', false);
            //        $("form").show();
            //    }
            //});

            $("#no").click(function () {
                if (this.checked) {
                    totali += parseFloat(jQuery(this).val());
                    $('#yes').prop('checked', false);
                    $("form").hide();
                }

            });
        });


        $("#yes").click(function () {
            if (this.checked) {
                $('#no').prop('checked', false);
                $("form").show();
            }
        });




    </script>

SwiftyNames.V1.0/SwiftyNames.V1.0/Views/NamesCatalog/CatalogView.cshtml
@model SwiftyNames.V1._0.Models.ChangeName
@{
    ViewBag.Title = "CatalogView";
    Layout = "~/Views/Shared/_Layout.cshtml";
    <link rel="stylesheet" type="text/css" href="/css/style.css" />
}
<div class="container">
    <div class="nav nav-bar">

        <div class="main-menu">

            <ul style="background: #02230c; ">
                <li><img src="/images/LOGO1.png" /></li>
                <li>@Html.ActionLink("HOME", "Index", "Home")</li>
                @*<li>@Html.ActionLink("ABOUT", "About", "Home")</li>*@
                <li class="active">@Html.ActionLink("CATALOGUE", "CatalogView", "NamesCatalog")</li>
                <li>@Html.ActionLink("CHANGE NAME", "NewsSearch", "Change")</li>
                <li>@Html.ActionLink("SEARCH NAMES", "SearchLogin", "Search")</li>
                <li>@Html.ActionLink("PUBLIC NOTICE", "PublicNewsSearch", "Home")</li>
                @*<li>@Html.ActionLink("FAQ", "Index", "Home")</li>*@

            </ul>
        </div> <!-- /.main-menu -->

    </div>
</div>
<div  style="margin-top:-13px;" class="container">
    <div class="mybox">
        <h2 style="font-family: 'Trebuchet MS'; text-shadow: 1px 1px 1px black;">Welcome!  Check our Catalogues of Name formats</h2>
    </div>


    <div class="box24">
        <div class="mybox1">
            <h3 style="margin-left: 0%; font-family: 'Trebuchet MS';">Name Catalogue </h3>
            <a class="btn-success form-control" style="color:white; text-align:center" href="~/Change/Change">CLICK HERE TO CHANGE NAME</a>
        </div>
        <div>
            <ul class="col-md-12 list-unstyled table-list" style="">
                <img class="slidr hidden-xs hidden-sm" style="float: right;" src="~/images/photo/name2.png" />
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI VICTOR. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as FASONU DEDEORI MAPAYI wish to inform the general public that my name is now FASONU OLASUNKANMI GBEMI. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as FRANKLYN REMILEKUN GLORIA wish to inform the general public that my name is now OLAWOYE REMILEKUN GLORIA. Thanks </liclass>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as BASOJE UWAKAGADO CYNTHIA wish to inform the general public that my name is now BASOJE GLORY CYNTHIA. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as OLA BABATUNJI OLUWAKAYODE wish to inform the general public that my name is now OLA TUNJI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
                <li class="col-md-3 well shrink" style="list-style: none; margin: .3%; text-align: justify; ">I, formerly known as AJAGBE AKINREMI ELERUJA wish to inform the general public that my name is now AJAGBE OLUREMI PROSPER. Thanks </li>
            </ul>

        </div>




        <div>


            @*@foreach (var list in ViewData["batch"] as List<SelectListItem>)
                {
                    var e = new List<string>();
                    <li style="display: block;height:15px;">@Html.CheckBox(list.Value)</li>
                    <li style="display: block; height: 15px; font-size: 12px;margin-left:25px;margin-top:-15px">@Html.Label(list.Text)</li>
                    e.Add(list.Selected.ToString());
                   TempData["r"] = e;

                }*@


        </div>
    </div>
</div>

SwiftyNames.V1.0/SwiftyNames.V1.0/Views/NamesCatalog/ChangeNameForm.cshtml
@*@model SwiftyNames.V1._0.Models.ChangeName
@{
    ViewBag.Title = "ChangeNameForm";
}

<h2>ChangeNameForm</h2>

        @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Change Of Name Form</h4>
                    <hr />
                    @Html.ValidationSummary(true)

                    <div class="form-group">
                        @Html.LabelFor(model => model.OldLastName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.OldLastName)
                            @Html.ValidationMessageFor(model => model.OldLastName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.OldFirstName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.OldFirstName)
                            @Html.ValidationMessageFor(model => model.OldFirstName)
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.NewLastName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NewLastName)
                            @Html.ValidationMessageFor(model => model.NewLastName)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.NewFirstName, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.NewFirstName)
                            @Html.ValidationMessageFor(model => model.NewFirstName)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Address, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Address)
                            @Html.ValidationMessageFor(model => model.Address)
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Phone, new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Phone)
                            @Html.ValidationMessageFor(model => model.Phone)
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
                            <div class="col-md-10">
                                @Html.EditorFor(model => model.Email)
                                @Html.ValidationMessageFor(model => model.Email)
                            </div>
                        </div>
                    </div>
                    <input type="file" name="uploadedFile" />
                    <br />
                    @Html.LabelFor(x => x.Prefferednews)
                    <br />
                    @Html.DropDownListFor(model => model.Prefferednews, Model.NewsPapers, "Select Dailies", new { @class = "form-control  input-lg" })
                    <br />
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Change" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }

            @section Scripts {
                @Scripts.Render("~/bundles/jqueryval")
            }*@

SwiftyNames.V1.0/SwiftyNames.V1.0/Views/NamesCatalog/ChangeOfNamey.cshtml
@{
    ViewBag.Title = "ChangeOfNamey";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ChangeOfNamey</h2>
<html>
@*<head>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="http://ajax.aspnetcdn.com/ajax/jquery.validate/1.13.1/jquery.validate.js"></script>
</head>*@
<body>
    <form method="POST" class="form" action="">
        <div class="step">Window 1</div>
        <div class="step">Window 2</div>
        <div class="step">Window 3</div>
        <div class="step">Window 4</div>
        <button type="button" class="action back">Back</button>
        <button type="button" class="action next">Next</button>
        <button type="button" class="action submit">Submit</button>

    </form>
</body>
</html>
<script>
$(document).ready(function(){
	var current = 1;

	widget      = $(".step");
	btnnext     = $(".next");
	btnback     = $(".back");
	btnsubmit   = $(".submit");

	// Init buttons and UI
	widget.not(':eq(0)').hide();
	hideButtons(current);
	setProgress(current);

	// Next button click action
	btnnext.click(function(){
		if(current < widget.length){
			// Check validation
			if($(".form").valid()){
				widget.show();
				widget.not(':eq('+(current++)+')').hide();
				setProgress(current);
			}
		}
		hideButtons(current);
	})

	// Back button click action
	btnback.click(function(){
		if(current > 1){
			current = current - 2;
			if(current < widget.length){
				widget.show();
				widget.not(':eq('+(current++)+')').hide();
				setProgress(current);
			}
		}
		hideButtons(current);
	})

	// Submit button click
	btnsubmit.click(function(){
		alert("Submit button clicked");
	});

    $('.form').validate({ // initialize plugin
		ignore:":not(:visible)",
		rules: {
			name : "required"
		},
    });

});

// Change progress bar action
setProgress = function(currstep){
	var percent = parseFloat(100 / widget.length) * currstep;
	percent = percent.toFixed();
	$(".progress-bar").css("width",percent+"%").html(percent+"%");
}

// Hide buttons according to the current step
hideButtons = function(current){
	var limit = parseInt(widget.length);

	$(".action").hide();

	if(current < limit) btnnext.show();
	if(current > 1) btnback.show();
	if (current == limit) {
		btnnext.hide();
		btnsubmit.show();
	}
}
</script>